{{- if .Values.supabase.kong.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: supaplus-kong-declarative-config-full
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/part-of: supaplus
    app.kubernetes.io/component: kong
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  kong.yml.tpl: |
    _format_version: "1.1"

    consumers:
      - username: anon
        keyauth_credentials:
            - key: {{ print "{{SUPABASE_ANON_KEY}}" }}
      - username: service_role
        keyauth_credentials:
            - key: {{ print "{{SUPABASE_SERVICE_KEY}}" }}

    acls:
      - consumer: anon
        group: anon
      - consumer: service_role
        group: admin

    services:
      - name: auth-v1-open
        url: http://{{ include "supabase.auth.fullname" .Subcharts.supabase }}:{{ .Values.supabase.auth.service.ports.http }}/verify
        routes:
          - name: auth-v1-open
            strip_path: true
            paths:
              - /auth/v1/verify
        plugins:
          - name: cors
      - name: auth-v1-open-callback
        url: http://{{ include "supabase.auth.fullname" .Subcharts.supabase }}:{{ .Values.supabase.auth.service.ports.http }}/callback
        routes:
          - name: auth-v1-open-callback
            strip_path: true
            paths:
              - /auth/v1/callback
        plugins:
          - name: cors
      - name: auth-v1-open-authorize
        url: http://{{ include "supabase.auth.fullname" .Subcharts.supabase }}:{{ .Values.supabase.auth.service.ports.http }}/authorize
        routes:
          - name: auth-v1-open-authorize
            strip_path: true
            paths:
              - /auth/v1/authorize
        plugins:
          - name: cors

      - name: auth-v1
        _comment: "GoTrue: /auth/v1/* -> http://{{ include "supabase.auth.fullname" .Subcharts.supabase }}:{{ .Values.supabase.auth.service.ports.http }}/*"
        url: http://{{ include "supabase.auth.fullname" .Subcharts.supabase }}:{{ .Values.supabase.auth.service.ports.http }}
        routes:
          - name: auth-v1-all
            strip_path: true
            paths:
              - /auth/v1/
        plugins:
          - name: cors
          - name: key-auth
            config:
              hide_credentials: false
          - name: acl
            config:
              hide_groups_header: true
              allow:
                - admin
                - anon

      - name: rest-v1
        _comment: "PostgREST: /rest/v1/* -> http://{{ include "supabase.rest.fullname" .Subcharts.supabase }}:{{ .Values.supabase.rest.service.ports.http }}/*"
        url: http://{{ include "supabase.rest.fullname" .Subcharts.supabase }}:{{ .Values.supabase.rest.service.ports.http }}/
        routes:
          - name: rest-v1-all
            strip_path: true
            paths:
              - /rest/v1/
        plugins:
          - name: cors
          - name: key-auth
            config:
              hide_credentials: true
          - name: acl
            config:
              hide_groups_header: true
              allow:
                - admin
                - anon

      - name: realtime-v1
        _comment: "Realtime: /realtime/v1/* -> ws://{{ include "supabase.realtime.fullname" .Subcharts.supabase }}:{{ .Values.supabase.realtime.service.ports.http }}/socket/*"
        url: http://{{ include "supabase.realtime.fullname" .Subcharts.supabase }}:{{ .Values.supabase.realtime.service.ports.http }}/socket
        routes:
          - name: realtime-v1-all
            strip_path: true
            paths:
              - /realtime/v1/
        plugins:
          - name: cors
          - name: key-auth
            config:
              hide_credentials: false
          - name: acl
            config:
              hide_groups_header: true
              allow:
                - admin
                - anon

      - name: storage-v1
        _comment: "Storage: /storage/v1/* -> http://{{ include "supabase.storage.fullname" .Subcharts.supabase }}:{{ .Values.supabase.storage.service.ports.http }}/*"
        url: http://{{ include "supabase.storage.fullname" .Subcharts.supabase }}:{{ .Values.supabase.storage.service.ports.http }}/
        routes:
          - name: storage-v1-all
            strip_path: true
            paths:
              - /storage/v1/
        plugins:
          - name: cors

      - name: meta
        _comment: "pg-meta: /pg/* -> http://{{ include "supabase.meta.fullname" .Subcharts.supabase }}:{{ .Values.supabase.meta.service.ports.http }}/*"
        url: http://{{ include "supabase.meta.fullname" .Subcharts.supabase }}:{{ .Values.supabase.meta.service.ports.http }}/
        routes:
          - name: meta-all
            strip_path: true
            paths:
              - /pg/
        plugins:
          - name: key-auth
            config:
              hide_credentials: false
          - name: acl
            config:
              hide_groups_header: true
              allow:
                - admin

      - name: functions-v1
        _comment: 'Edge Functions: /functions/v1/* -> http://{{ include "supaplus.functions.fullname" . }}:{{ .Values.functions.service.ports.http }}/*'
        url: http://{{ include "supaplus.functions.fullname" . }}:{{ .Values.functions.service.ports.http }}/
        routes:
          - name: functions-v1-all
            strip_path: true
            paths:
              - /functions/v1/
        plugins:
          - name: cors

    {{- if .Values.analytics.enabled }}
      - name: analytics-v1
        _comment: 'Analytics: /analytics/v1/* -> http://{{ include "supaplus.analytics.fullname" . }}:{{ .Values.analytics.service.ports.http }}/*'
        url: http://{{ include "supaplus.analytics.fullname" . }}:{{ .Values.analytics.service.ports.http }}/
        routes:
          - name: analytics-v1-all
            strip_path: true
            paths:
              - /analytics/v1/
    {{- end }}

{{- end }}
