{{- if .Values.studio.enabled }}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "supabase.studio.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/part-of: supabase
    app.kubernetes.io/component: studio
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.studio.replicaCount }}
  {{- if .Values.studio.updateStrategy }}
  strategy: {{- toYaml .Values.studio.updateStrategy | nindent 4 }}
  {{- end }}
  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.studio.podLabels .Values.commonLabels ) "context" . ) }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 6 }}
      app.kubernetes.io/component: studio
  template:
    metadata:
      annotations:
        {{- if .Values.studio.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.studio.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
        checksum/default-configmap: {{ include (print $.Template.BasePath "/studio/default-configmap.yaml") . | sha256sum }}
        {{- if .Values.studio.extraConfig }}
        checksum/extra-configmap: {{ include (print $.Template.BasePath "/studio/extra-configmap.yaml") . | sha256sum }}
        {{- end }}
        {{- $ns := include "common.names.namespace" . -}}
        {{- $jwtSec := lookup "v1" "Secret" $ns (include "supabase.jwt.secretName" .) -}}
        {{- if $jwtSec }}
        checksum/jwt-secret: {{ toYaml $jwtSec.data | sha256sum }}
        {{- end }}
      labels: {{- include "common.labels.standard" ( dict "customLabels" $podLabels "context" $ ) | nindent 8 }}
        app.kubernetes.io/part-of: supabase
        app.kubernetes.io/component: studio
    spec:
      serviceAccountName: {{ template "supabase.serviceAccountName" . }}
      {{- include "supabase.imagePullSecrets" . | nindent 6 }}
      automountServiceAccountToken: {{ .Values.studio.automountServiceAccountToken }}
      {{- if .Values.studio.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.studio.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.studio.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.studio.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.studio.podAffinityPreset "component" "studio" "customLabels" $podLabels "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.studio.podAntiAffinityPreset "component" "studio" "customLabels" $podLabels "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.studio.nodeAffinityPreset.type "key" .Values.studio.nodeAffinityPreset.key "values" .Values.studio.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.studio.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.studio.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.studio.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.studio.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.studio.priorityClassName }}
      priorityClassName: {{ .Values.studio.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.studio.schedulerName }}
      schedulerName: {{ .Values.studio.schedulerName | quote }}
      {{- end }}
      {{- if .Values.studio.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.studio.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.studio.podSecurityContext.enabled }}
      securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.studio.podSecurityContext "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.studio.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.studio.terminationGracePeriodSeconds }}
      {{- end }}
      initContainers:
        {{- if not .Values.diagnosticMode.enabled }}
        {{- include "supabase.database.checkdbready" . | nindent 8 }}
        {{- end }}
        {{- if .Values.studio.initContainers }}
          {{- include "common.tplvalues.render" (dict "value" .Values.studio.initContainers "context" $) | nindent 8 }}
        {{- end }}
      containers:
        - name: supabase-studio
          image: {{ template "supabase.studio.image" . }}
          imagePullPolicy: {{ .Values.studio.image.pullPolicy }}
          {{- if .Values.studio.containerSecurityContext.enabled }}
          securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.studio.containerSecurityContext "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.studio.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.studio.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.studio.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.studio.args "context" $) | nindent 12 }}
          {{- end }}
          env:
            {{ include "supabase.database.envvars" . | indent 12 }}

            - name: SUPABASE_ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.jwt.secretName" . }}
                  key: {{ include "supabase.jwt.anonSecretKey" . }}
            - name: SUPABASE_SERVICE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.jwt.secretName" . }}
                  key: {{ include "supabase.jwt.serviceSecretKey" . }}
            - name: SUPABASE_KEY_ADMIN
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.jwt.secretName" . }}
                  key: {{ include "supabase.jwt.serviceSecretKey" . }}

            - name: HOSTNAME
              # FIXME: this is a hack for when ipv6 is disabled in the container runtime/host
              value: "0.0.0.0"
            #   value: "::"

            - name: PG_META_CRYPTO_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.meta.existingSecret }}
                  key: {{ .Values.meta.existingSecretKey }}

            - name: SUPABASE_URL
              value: {{ include "supabase.api.baseHttp" . | quote }}
            - name: STUDIO_PG_META_URL
              value: {{ printf "%s/pg" (include "supabase.api.baseHttp" .) | quote }}
            - name: SUPABASE_PUBLIC_URL
              value: {{ include "supabase.api.publicURL" . | quote }}
            - name: PORT
              value: {{ .Values.studio.containerPorts.http | quote }}

            # FIXME: is this necessary?
            - name: CURRENT_CLI_VERSION
              value: "2.53.6"

            # FIXME: nasty hack, make this configurable!!!
            - name: EDGE_FUNCTIONS_MANAGEMENT_FOLDER
              value: /functions

            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.s3.accessKey.secretname | default "s3-storage" }}
                  key: {{ .Values.s3.accessKey.keyname | default "username" }}
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.s3.secretKey.secretname | default "s3-storage" }}
                  key: {{ .Values.s3.secretKey.keyname | default "password" }}

            {{- if .Values.analytics.enabled }}
            - name: LOGFLARE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.analytics.secretName" . }}
                  key: {{ include "supabase.analytics.apiSecretKey" . }}

            - name: LOGFLARE_PUBLIC_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.analytics.secretName" . }}
                  key: {{ include "supabase.analytics.apiSecretKey" . }}

            - name: LOGFLARE_PRIVATE_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.analytics.secretName" . }}
                  key: {{ include "supabase.analytics.apiPrivateSecretKey" . }}

            - name: NEXT_ANALYTICS_BACKEND_PROVIDER
              value: {{ .Values.studio.analytics.backendProvider | quote }}
            - name: LOGFLARE_URL
              value: "http://{{ include "supabase.analytics.fullname" . }}:{{ .Values.analytics.service.ports.http }}"
            - name: NEXT_PUBLIC_ENABLE_LOGS
              value: "true"
            {{- end }}

            {{- if .Values.studio.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.studio.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "supabase.studio.defaultConfigmapName" . }}
            {{- if .Values.studio.extraConfigExistingConfigmap }}
            - configMapRef:
                name: {{ include "supabase.studio.extraConfigmapName" . }}
            {{- end }}
            {{- if .Values.studio.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.studio.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.studio.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.studio.extraEnvVarsSecret "context" $) }}
            {{- end }}
          {{- if .Values.studio.resources }}
          resources: {{- toYaml .Values.studio.resources | nindent 12 }}
          {{- end }}
          ports:
            - name: http-studio
              containerPort: {{ .Values.studio.containerPorts.http }}
          {{- if not .Values.diagnosticMode.enabled }}
          {{- if .Values.studio.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.studio.customLivenessProbe "context" $) | nindent 12 }}
          {{- else if .Values.studio.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.studio.livenessProbe "enabled") "context" $) | nindent 12 }}
            tcpSocket:
              port: http-studio
          {{- end }}
          {{- if .Values.studio.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.studio.customReadinessProbe "context" $) | nindent 12 }}
          {{- else if .Values.studio.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.studio.readinessProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /
              port: http-studio
          {{- end }}
          {{- if .Values.studio.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.studio.customStartupProbe "context" $) | nindent 12 }}
          {{- else if .Values.studio.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.studio.startupProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /
              port: http-studio
          {{- end }}
          {{- end }}
          {{- if .Values.studio.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.studio.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: empty-dir
              mountPath: /tmp
              subPath: tmp-dir
            {{- if .Values.functions.imageVolume.enabled }}
            - name: functions-static
              # FIXME: make me configurable!!!
              mountPath: /functions | quote }}
              readOnly: true
            {{- end }}
          {{- if .Values.studio.extraVolumeMounts }}
          {{- include "common.tplvalues.render" (dict "value" .Values.studio.extraVolumeMounts "context" $) | nindent 12 }}
          {{- end }}
        {{- if .Values.studio.sidecars }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.studio.sidecars "context" $) | nindent 8 }}
        {{- end }}
      volumes:
        - name: empty-dir
          emptyDir: {}
        {{- if .Values.functions.imageVolume.enabled }}
        - name: functions-static
          image:
            reference: {{ include "supabase.functions.imageVolume" . }}
            pullPolicy: {{ .Values.functions.imageVolume.image.pullPolicy | quote }}
        {{- end }}

        {{- if .Values.studio.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.studio.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
{{- end }}
