{{- if and .Values.gateway.tls.enabled .Values.gateway.tls.certManager.enabled }}
{{- $tlsHosts := concat (.Values.gateway.tls.hosts | default list) (.Values.gateway.tls.extraHosts | default list) -}}
{{- $certMan := .Values.gateway.tls.certManager -}}
{{- $base := .Values -}}
{{- $ns := include "supabase.gateway.ingress.namespace" . -}}
{{- range $host := $tlsHosts }}
{{- $credentialName := $host.credentialName -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $credentialName }}
  namespace: {{ $ns }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $base.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/part-of: supabase
    app.kubernetes.io/component: ingress
spec:
  secretName: {{ $credentialName }}
  dnsNames:
    - {{ $host.name }}
  issuerRef:
    name: {{ required "You must set gateway.tls.certManager.issuerRef.name when enabling cert-manager certificate." $certMan.issuerRef.name | quote }}
    kind: {{ $certMan.issuerRef.kind | default "ClusterIssuer" | quote }}
    {{- if $certMan.issuerRef.group }}
    group: {{ $certMan.issuerRef.group | quote }}
    {{- end }}
  {{- if $certMan.duration }}
  duration: {{ $certMan.duration | quote }}
  {{- end }}
  {{- if $certMan.renewBefore }}
  renewBefore: {{ $certMan.renewBefore | quote }}
  {{- end }}
  privateKey:
    algorithm: {{ $certMan.privateKey.algorithm | default "RSA" | quote }}
    size: {{ $certMan.privateKey.size | default 2048 }}
---
{{- end }}
{{- end }}
