{{- if .Values.garage.backups.listenerset.enabled }}
{{- $hosts := concat (.Values.gateway.hosts | default list) (.Values.gateway.extraHosts | default list) -}}

{{- range $host := $hosts }}
kind: ListenerSet
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: {{ $host.name }}
  {{- if $host.annotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" $host.annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  parentRef:
    name: {{ .Values.gateway.name }}
    namespace: {{ .Values.gateway.namespace }}
  listeners:
  - name: {{ (printf "http-%s" ($host | replace "." "-")) | quote }}
    hostname: {{ $host | quote }}
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All

  {{- if $host.tlsEnabled }}
    - name: https
      hostname: {{ $host.name }}
      port: {{ $host.tls.port }}
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ $host.tls.certName }}
  {{- end }}
    - name: http
      hostname: {{ $host.name }}
      port: {{ $host.port }}
      protocol: HTTP
{{- end }}
{{- end }}