{{- if .Values.kong.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supabase.kong.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  {{- if not .Values.kong.autoscaling.enabled }}
  replicas: {{ .Values.kong.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "supabase.kong.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.kong.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "supabase.kong.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.kong.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "supabase.kong.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.kong.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "supabase.kong.name" $ }}
          securityContext:
            {{- toYaml .Values.kong.securityContext | nindent 12 }}
          image: "{{ .Values.kong.image.repository }}:{{ .Values.kong.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.kong.image.pullPolicy }}

          {{- if .Values.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.kong.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.kong.command "context" $) | nindent 12 }}
          {{- else }}
          command: ["/bin/bash"]
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.kong.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.kong.args "context" $) | nindent 12 }}
          {{- else }}
          args: ["/scripts/wrapper.sh"]
          {{- end }}

          env:
            - name: KONG_DATABASE
              value: "off"

            - name: KONG_DECLARATIVE_CONFIG
            {{- if .Values.kong.declarativeConfig }}
              value: {{ .Values.kong.declarativeConfig }}
            {{- else }}
              value: /usr/local/kong/kong.yml
            {{- end }}
            - name: KONG_DNS_ORDER
            {{- if .Values.kong.dnsOrder }}
              value: {{ .Values.kong.dnsOrder }}
            {{- else }}
              value: LAST,A,CNAME
            {{- end }}
            - name: KONG_PLUGINS
            {{- if .Values.kong.plugins }}
              value: {{ .Values.kong.plugins | join "," }}
            {{- else }}
              # value: request-transformer,cors,key-auth,acl
              value: request-transformer,cors,key-auth,acl,basic-auth
            {{- end }}
            - name: KONG_NGINX_PROXY_BUFFER_SIZE
            {{- if .Values.kong.nginxProxyBufferSize }}
              value: {{ .Values.kong.nginxProxyBufferSize }}
            {{- else }}
              value: 160k
            {{- end }}
            - name: KONG_NGINX_PROXY_BUFFERS
            {{- if .Values.kong.nginxProxyBuffers }}
              value: {{ .Values.kong.nginxProxyBuffers }}
            {{- else }}
              value: "64 160k"
            {{- end }}
            - name: KONG_LOG_LEVEL
            {{- if .Values.kong.logLevel }}
              value: {{ .Values.kong.logLevel }}
            {{- else }}
              value: warn
            {{- end }}

            {{- if .Values.kong.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.kong.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}

            - name: SUPABASE_ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: '{{ include "supabase.jwt.secretName" . }}'
                  key: '{{ include "supabase.jwt.anonSecretKey" . }}'
            - name: SUPABASE_SERVICE_KEY
              valueFrom:
                secretKeyRef:
                  name: '{{ include "supabase.jwt.secretName" . }}'
                  key: '{{ include "supabase.jwt.serviceSecretKey" . }}'

          {{- with .Values.kong.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.kong.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          {{- with .Values.kong.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /usr/local/kong/template.yml
              name: config
              subPath: template.yml
            - mountPath: /scripts
              name: wrapper
            {{- with .Values.kong.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with .Values.kong.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kong.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kong.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "supabase.kong.fullname" $ }}
            defaultMode: 0777
            items:
            - key: template.yml
              path: template.yml
        - name: wrapper
          configMap:
            name: {{ include "supabase.kong.fullname" $ }}
            defaultMode: 0777
            items:
            - key: wrapper.sh
              path: wrapper.sh
        {{- with .Values.kong.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}