{{- if .Values.supabase.studio.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: supaplus-supabase-studio-default-full
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/part-of: supaplus
    app.kubernetes.io/component: studio
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data: {{- include "common.tplvalues.render" (dict "value" .Values.supabase.studio.defaultConfigFull "context" $) | nindent 2 }}
{{- end }}
