{{- if and .Values.istio.enabled .Values.istio.gateway.create }}
{{- /* Compute name (allow override) */ -}}
{{- $autoName := printf "%s-gateway" (include "common.names.fullname" .) -}}
{{- $gwName := .Values.istio.gateway.name | default $autoName -}}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ $gwName }}
  namespace: {{ .Values.istio.gateway.namespace | default (include "supabase.istio.ingress.namespace" .) }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/part-of: supabase
    app.kubernetes.io/component: ingress
spec:
  gatewayClassName: istio
  listeners:
    # FIXME: I need to add the internalservice.yaml here!!!

    {{- $hosts := .Values.istio.hosts | default (list) }}
    - name: http
      {{- if eq (len $hosts) 1 }}
      hostname: {{ index $hosts 0 | quote }}
      {{- end }}
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: {{ .Values.istio.gateway.allowedRoutes.namespaces.from | default "All" | quote }}
    {{- if .Values.istio.tls.enabled }}
    - name: https
      {{- if eq (len $hosts) 1 }}
      hostname: {{ index $hosts 0 | quote }}
      {{- end }}
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: {{ .Values.istio.tls.credentialName | default (printf "%s-tls" (include "common.names.fullname" .)) }}
      allowedRoutes:
        namespaces:
          from: {{ .Values.istio.gateway.allowedRoutes.namespaces.from | default "All" | quote }}
    {{- end }}
{{- end }}
