apiVersion: v1
kind: Service
metadata:
  name: supabase-internal
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/part-of: supabase
    app.kubernetes.io/component: ingress
spec:
  type: ExternalName
  externalName: {{ include "supabase.gateway.ingress.fqdn" . }}
