{{- if .Values.istio.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-preflight-shim
  namespace: {{ include "common.names.namespace" . }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/part-of: supabase
    app.kubernetes.io/component: preflight-shim
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 8080;
        # Always return 204 (No Content) for any request. Headers are injected by HTTPRoute filters.
        return 204;
      }
    }
{{- end }}
