{{- if and .Values.istio.enabled .Values.istio.redirect.enabled .Values.gateway.existing.name }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "common.names.fullname" . }}-redirect
  namespace: {{ include "common.names.namespace" . }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/part-of: supabase
    app.kubernetes.io/component: ingress
spec:
  parentRefs:
    - kind: ListenerSet
      name: {{ .Values.gateway.listenerset.name | default (printf "%s-gateway" (include "common.names.fullname" .)) }}

  # parentRefs:
  #   - group: gateway.networking.k8s.io
  #     kind: Gateway
  #     name: {{ .Values.gateway.existing.name }}
  #     namespace: {{ .Values.gateway.existing.namespace | default (include "supabase.istio.ingress.namespace" .) }}
  hostnames:
    {{- include "supabase.istio.validatedHosts" . | nindent 4 }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: {{ .Values.istio.redirect.statusCode | default 308 }}
{{- end }}
