apiVersion: v2
name: supaplus
description: A Helm chart for Kubernetes to deploy Bitnami Supabase with the missing features added
type: application
version: 0.0.5
appVersion: "4.0.x"

dependencies:
  - name: supabase
    version: 4.x
    repository: https://charts.bitnami.com/bitnami

  - name: postgresql
    version: 15.x
    alias: analyticsdb
    repository: https://charts.bitnami.com/bitnami
    condition: analyticsdb.enabled

  - name: minio
    version: 14.x
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled

  - name: common
    version: 2.x.x
    repository: https://charts.bitnami.com/bitnami

  - name: vector
    version: 0.x.x
    repository: https://helm.vector.dev
    condition: analytics.enabled
