{{- if and .Values.analytics.enabled (not .Values.analytics.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.analytics.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  api-key: {{ include "common.secrets.passwords.manage" (dict "secret" (include "supabase.analytics.secretName" .) "key" "api-key" "providedValues" (list "analytics.apiKey") "length" 32 "context" $) }}
{{- end }}
