annotations:
  licenses: Apache-2.0
apiVersion: v2
appVersion: 1.24.4
dependencies:
- name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 15.x.x
  condition: postgresql.enabled
- name: postgresql
  version: 15.x
  alias: analyticsdb
  repository: https://charts.bitnami.com/bitnami
  condition: analyticsdb.enabled
- name: kong
  repository: https://charts.bitnami.com/bitnami
  version: 12.x.x
  condition: kong.enabled
- name: minio
  version: 14.x
  repository: https://charts.bitnami.com/bitnami
  condition: minio.enabled
- name: vector
  version: 0.x.x
  repository: https://helm.vector.dev
  condition: analytics.enabled
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 2.x.x

description: Supabase is an open source Firebase alternative. Provides all the necessary backend features to build your application in a scalable way. Uses PostgreSQL as datastore.
home: https://github.com/supafull/
keywords:
- development
- dashboards
maintainers:
- name: Anton MELSER
  url: https://github.com/AntonOfTheWoods
name: supabase
sources:
- https://github.com/supafull/supabase
version: 0.0.7
